# Multiple Regression

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Import dataset

In [29]:
# Importing the dataset
dataset = pd.read_csv('Multiple_Linear_Regression/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
print('X: \n{}'.format(X[0:5,]))
print('y: \n{}'.format(y[0:5]))

X: 
[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
y: 
[ 192261.83  191792.06  191050.39  182901.99  166187.94]


### Convert category column to dummy variable

In [30]:
# Convert state column to a dummy variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3],
                             dtype='int_')
X = onehotencoder.fit_transform(X).toarray()

print('X: \n{}'.format(X[0:5,]))


X: 
[[  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.65349200e+05
    1.36897800e+05   4.71784100e+05]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   1.62597700e+05
    1.51377590e+05   4.43898530e+05]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.53441510e+05
    1.01145550e+05   4.07934540e+05]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.44372410e+05
    1.18671850e+05   3.83199620e+05]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.42107340e+05
    9.13917700e+04   3.66168420e+05]]


### Avoid the dummy variable trap (exclude one dummy variable)

In [31]:
# Avoiding the dummy variable trap 
# (usually this does not need to be done explicityly)
X = X[:, 1:]
X


array([[  0.00000000e+00,   1.00000000e+00,   1.65349200e+05,
          1.36897800e+05,   4.71784100e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.62597700e+05,
          1.51377590e+05,   4.43898530e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.53441510e+05,
          1.01145550e+05,   4.07934540e+05],
       [  0.00000000e+00,   1.00000000e+00,   1.44372410e+05,
          1.18671850e+05,   3.83199620e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.42107340e+05,
          9.13917700e+04,   3.66168420e+05],
       [  0.00000000e+00,   1.00000000e+00,   1.31876900e+05,
          9.98147100e+04,   3.62861360e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.34615460e+05,
          1.47198870e+05,   1.27716820e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.30298130e+05,
          1.45530060e+05,   3.23876680e+05],
       [  0.00000000e+00,   1.00000000e+00,   1.20542520e+05,
          1.48718950e+05,   3.11613290e+05],
       [  0.00000000e+00,   0.0000000

### Train/Test Split

In [32]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### !Don't need to do feature scaling as the library will do this for us!

### Want the model to predict the profit of a startup given the features


In [33]:
# Fit the regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [34]:
# Use the model to predict the test variables
y_pred = regressor.predict(X_test)
y_pred

array([ 103015.20159796,  132582.27760815,  132447.73845175,
         71976.09851258,  178537.48221056,  116161.24230166,
         67851.69209676,   98791.73374687,  113969.43533013,
        167921.06569551])

In [35]:
y_test

array([ 103282.38,  144259.4 ,  146121.95,   77798.83,  191050.39,
        105008.31,   81229.06,   97483.56,  110352.25,  166187.94])

In [36]:
y_diff = y_test - y_pred
y_diff

array([   267.17840204,  11677.12239185,  13674.21154825,   5822.73148742,
        12512.90778944, -11152.93230166,  13377.36790324,  -1308.17374687,
        -3617.18533013,  -1733.12569551])

In [37]:
y_percentage = (y_diff/y_test)*100
y_percentage

array([  0.2586873 ,   8.09453137,   9.35808176,   7.48434326,
         6.54953271, -10.62099971,  16.46869717,  -1.34194294,
        -3.27785372,  -1.04287092])

In [38]:
# The difference between predicted to actual
print('test | pred | %')
for i in range(len(y_test)):
    print('{:.2f} | {:.2f} | {:.2f}'.format(y_test[i], y_pred[i], y_percentage[i] ))
    

test | pred | %
103282.38 | 103015.20 | 0.26
144259.40 | 132582.28 | 8.09
146121.95 | 132447.74 | 9.36
77798.83 | 71976.10 | 7.48
191050.39 | 178537.48 | 6.55
105008.31 | 116161.24 | -10.62
81229.06 | 67851.69 | 16.47
97483.56 | 98791.73 | -1.34
110352.25 | 113969.44 | -3.28
166187.94 | 167921.07 | -1.04


### Backwards elimination

In [39]:
import statsmodels.formula.api as sm

# Add a column of ones - the y-intercept (statsmodels requires this)
# This adds ones at the start of the matrix 
X = np.append(arr=np.ones((50,1)).astype(int), values=X, axis=1)
X[0]

array([  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
         1.65349200e+05,   1.36897800e+05,   4.71784100e+05])

In [40]:
# Fit the OLS model
X_optimal = X[:, [0,1,2,3,4,5]]
regressor_OLS = sm.OLS(endog=y, exog=X_optimal).fit()

In [41]:
# Get the summary of the OLS model
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Thu, 26 Apr 2018   Prob (F-statistic):           1.34e-27
Time:                        16:46:30   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000      3.62e+04   6.4e+04
x1           198.7888   3371.007      0.059      0.953     -6595.030  6992.607
x2           -41.8870   3256.039     -0.013      0.990     -6604.003  6520.229
x3             0.8060      0.046     17.369      0.000         0.712     0.900
x4            -0.0270      0.052     -0.517      0.608        -0.132     0.078
x5             0.0270      0.017      1.574      0.123        -0.008     0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [42]:
# Now remove the 'x2' variable (because p>= 0.05)
X_optimal = X[:, [0,1,3,4,5]]
regressor_OLS = sm.OLS(endog=y, exog=X_optimal).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Thu, 26 Apr 2018   Prob (F-statistic):           8.49e-29
Time:                        16:48:19   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000      3.67e+04  6.35e+04
x1           220.1585   2900.536      0.076      0.940     -5621.821  6062.138
x2             0.8060      0.046     17.606      0.000         0.714     0.898
x3            -0.0270      0.052     -0.523      0.604        -0.131     0.077
x4             0.0270      0.017      1.592      0.118        -0.007     0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [43]:
# Now remove the 'x1' variable (because p>= 0.05)
X_optimal = X[:, [0,3,4,5]]
regressor_OLS = sm.OLS(endog=y, exog=X_optimal).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Thu, 26 Apr 2018   Prob (F-statistic):           4.53e-30
Time:                        16:48:38   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000      3.69e+04  6.34e+04
x1             0.8057      0.045     17.846      0.000         0.715     0.897
x2            -0.0268      0.051     -0.526      0.602        -0.130     0.076
x3             0.0272      0.016      1.655      0.105        -0.006     0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [44]:
# Now remove the 'x1' variable (because p>= 0.05)
X_optimal = X[:, [0,3,5]]
regressor_OLS = sm.OLS(endog=y, exog=X_optimal).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Thu, 26 Apr 2018   Prob (F-statistic):           2.16e-31
Time:                        16:49:19   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000      4.16e+04  5.24e+04
x1             0.7966      0.041     19.266      0.000         0.713     0.880
x2             0.0299      0.016      1.927      0.060        -0.001     0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [45]:
# Now remove the 'x1' variable (because p>= 0.05)
X_optimal = X[:, [0,3]]
regressor_OLS = sm.OLS(endog=y, exog=X_optimal).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Thu, 26 Apr 2018   Prob (F-statistic):           3.50e-32
Time:                        16:50:00   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000      4.39e+04  5.41e+04
x1             0.8543      0.029     29.151      0.000         0.795     0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [46]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_optimal, y, test_size = 0.2, random_state = 0)

# Fit the regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Use the model to predict the test variables
y_pred = regressor.predict(X_test)
y_diff = y_test - y_pred
y_percentage = (y_diff/y_test)*100

# The difference between predicted to actual
print('test | pred | %')
for i in range(len(y_test)):
    print('{:.2f} | {:.2f} | {:.2f}'.format(y_test[i], y_pred[i], y_percentage[i] ))
    

test | pred | %
103282.38 | 104667.28 | -1.34
144259.40 | 134150.83 | 7.01
146121.95 | 135207.80 | 7.47
77798.83 | 72170.54 | 7.23
191050.39 | 179090.59 | 6.26
105008.31 | 109824.77 | -4.59
81229.06 | 65644.28 | 19.19
97483.56 | 100481.43 | -3.08
110352.25 | 111431.75 | -0.98
166187.94 | 169438.15 | -1.96
