# Data pre-processing tricks

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

print('X: \n{}\n'.format(X[:]))
print('y: \n{}\n'.format(y))

X: 
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

y: 
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']



In [11]:
# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print('X: \n{}\n'.format(X[:]))

X: 
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]



In [19]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
print('X: \n{}\n'.format(X[:,:3]))
print('X: \n{}\n'.format(X[:, -2:]))

X: 
[[ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 1.  0.  1.]
 [ 1.  0.  1.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]]

X: 
[[  4.40000000e+01   7.20000000e+04]
 [  2.70000000e+01   4.80000000e+04]
 [  3.00000000e+01   5.40000000e+04]
 [  3.80000000e+01   6.10000000e+04]
 [  4.00000000e+01   6.37777778e+04]
 [  3.50000000e+01   5.80000000e+04]
 [  3.87777778e+01   5.20000000e+04]
 [  4.80000000e+01   7.90000000e+04]
 [  5.00000000e+01   8.30000000e+04]
 [  3.70000000e+01   6.70000000e+04]]



In [20]:
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])